'use strict';
// سجل القادة لكل سيناريو. «bio» مادة موثقة مختصرة بصياغة أصلية (مراجعة على ويكيبيديا).
// المولد يُذكر فقط حين يكون معروفاً. المرشح لا يظهر قبل سنة «from» ولا بعد «to» ولا بعد وفاته،
// ولا يظهر إن كان عمره أقل من 16 سنة. ما يفعله القائد في الحملة (السمات والولاء والمصير) محاكاة لا تاريخ.
// at: مملكة (في بلاطها منذ البداية) أو 'cand' (مرشح في فرص الاستقطاب) أو 'neutral' أو 'event' (قادة الأحداث)
const CMD_CATALOG = {
 "threeKingdoms": [
  {
   "n": "ليو باي",
   "trait": "merchant",
   "flaw": null,
   "lead": 3,
   "fame": 70,
   "src": "hist",
   "wiki": "Liu_Bei",
   "ar": "ليو باي",
   "bio": "أمير حرب من أواخر أسرة هان الشرقية، أسّس دولة شو هان وصار أول أباطرتها سنة 221.",
   "born": 161,
   "at": "shu",
   "ruler": true,
   "died": 223
  },
  {
   "n": "قوان يو",
   "trait": "brave",
   "flaw": "arrogant",
   "lead": 4,
   "fame": 70,
   "src": "hist",
   "wiki": "Guan_Yu",
   "ar": "كوان يو",
   "bio": "من أوائل أتباع ليو باي مع جانغ في. قاد جبهة جينغ حتى أسرته قوات سون تشوان وقتلته مطلع سنة 220.",
   "at": "shu",
   "died": 220
  },
  {
   "n": "جانغ في",
   "trait": "brave",
   "flaw": "harsh",
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Zhang_Fei",
   "ar": "جانغ فاي",
   "bio": "قائد وسياسي في خدمة ليو باي منذ بداياته، ومات سنة 221.",
   "at": "shu",
   "died": 221
  },
  {
   "n": "جاو يون",
   "trait": "cavalier",
   "flaw": null,
   "lead": 4,
   "fame": 70,
   "src": "hist",
   "wiki": "Zhao_Yun",
   "ar": "جاو يون",
   "bio": "كان تابعاً لأمير الحرب الشمالي غونغسون زان قبل أن يلتحق بليو باي، وخدم شو حتى وفاته سنة 229.",
   "at": "shu",
   "died": 229
  },
  {
   "n": "جوغه ليانغ",
   "trait": "elite",
   "flaw": null,
   "lead": 5,
   "fame": 70,
   "src": "hist",
   "wiki": "Zhuge_Liang",
   "ar": "تشوغ ليانغ",
   "bio": "رجل دولة واستراتيجي عاش انهيار أسرة هان، والمهندس الأول لدولة شو هان حتى وفاته سنة 234.",
   "born": 181,
   "at": "shu",
   "died": 234
  },
  {
   "n": "هوانغ جونغ",
   "trait": "archer",
   "flaw": null,
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Huang_Zhong",
   "ar": null,
   "bio": "قائد في خدمة ليو باي، اشتهر بانتصاره في معركة جبل دينغجون سنة 219 التي قُتل فيها قائد وي شياهو يوان.",
   "at": "shu",
   "died": 220
  },
  {
   "n": "وي يان",
   "trait": "mountaineer",
   "flaw": "arrogant",
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Wei_Yan",
   "ar": null,
   "bio": "بدأ تابعاً لليو باي ثم صار قائداً وسياسياً بارزاً في شو هان، ومات نحو سنة 234.",
   "at": "cand",
   "aff": "shu",
   "from": 208,
   "to": 234,
   "died": 234
  },
  {
   "n": "ما ليانغ",
   "trait": "logistician",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Ma_Liang_(Three_Kingdoms)",
   "ar": null,
   "bio": "مسؤول في خدمة ليو باي اشتهر بموهبته منذ صغره، وقُتل في معركة شياوتينغ سنة 222.",
   "born": 187,
   "at": "cand",
   "aff": "shu",
   "from": 208,
   "to": 222,
   "died": 222
  },
  {
   "n": "بانغ تونغ",
   "trait": "tactician",
   "flaw": null,
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Pang_Tong",
   "ar": "بانغ تونغ",
   "bio": "مستشار رئيسي لليو باي، استُخفّ به في صباه لبساطة مظهره. مات سنة 214.",
   "born": 179,
   "at": "cand",
   "aff": "shu",
   "from": 209,
   "to": 214,
   "died": 214
  },
  {
   "n": "فا جنغ",
   "trait": "tactician",
   "flaw": null,
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Fa_Zheng",
   "ar": null,
   "bio": "من أسرة عريقة، رحل إلى إقليم يي في خدمة ليو جانغ ثم صار مستشاراً رئيسياً لليو باي.",
   "born": 176,
   "at": "cand",
   "aff": "shu",
   "from": 211,
   "to": 220,
   "died": 220
  },
  {
   "n": "ما تشاو",
   "trait": "cavalier",
   "flaw": "reckless",
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Ma_Chao",
   "ar": null,
   "bio": "من نسل القائد ما يوان وأكبر أبناء ما تنغ. هُزم أمام تساو تساو في معبر تونغ سنة 211، ثم انضم إلى ليو باي.",
   "born": 176,
   "at": "cand",
   "aff": "shu",
   "from": 212,
   "to": 222,
   "died": 222
  },
  {
   "n": "وانغ بينغ",
   "trait": "defender",
   "flaw": null,
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Wang_Ping_(Three_Kingdoms)",
   "ar": null,
   "bio": "ضابط في جيش تساو تساو انشق إلى ليو باي في حملة هانزونغ سنة 219، ولم يتعلم القراءة لأنه دخل الجيش صغيراً.",
   "at": "cand",
   "aff": "shu",
   "from": 219,
   "to": 248,
   "died": 248
  },
  {
   "n": "جيانغ وي",
   "trait": "mountaineer",
   "flaw": null,
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Jiang_Wei",
   "ar": null,
   "bio": "وُلد سنة 202 في مقاطعة جي، وصار من أبرز قادة شو هان وسياسييها.",
   "born": 202,
   "at": "cand",
   "aff": "shu",
   "from": 228,
   "to": 264,
   "died": 264
  },
  {
   "n": "ما داي",
   "trait": "cavalier",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Ma_Dai",
   "ar": null,
   "bio": "خدم عمّه ما تنغ في الشمال الغربي ثم صار قائداً في شو هان.",
   "at": "cand",
   "aff": "shu",
   "from": 214,
   "to": 235,
   "died": 235
  },
  {
   "n": "لي يان",
   "trait": "logistician",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Li_Yan_(Three_Kingdoms)",
   "ar": null,
   "bio": "قائد في شو هان، ويُعرف أيضاً باسم لي بينغ. بلغ ذروة مسيرته حين عُهد إليه بالوصاية مع جوغه ليانغ.",
   "at": "cand",
   "aff": "shu",
   "from": 214,
   "to": 231,
   "died": 231
  },
  {
   "n": "منغ دا",
   "trait": "swift",
   "flaw": "disloyal",
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Meng_Da",
   "ar": null,
   "bio": "خدم ليو جانغ ثم ليو باي، وانشق إلى وي، ثم ثار عليها نحو سنة 227 ساعياً إلى العودة لشو.",
   "at": "cand",
   "from": 211,
   "to": 228,
   "died": 228
  },
  {
   "n": "هوانغ تشيوان",
   "trait": "defender",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Huang_Quan_(general)",
   "ar": null,
   "bio": "خدم ليو جانغ ثم ليو باي الذي اعتمد عليه، ثم انتقل إلى وي.",
   "at": "cand",
   "from": 214,
   "to": 240,
   "died": 240
  },
  {
   "n": "ليو با",
   "trait": "merchant",
   "flaw": null,
   "lead": 1,
   "fame": 30,
   "src": "hist",
   "wiki": "Liu_Ba",
   "ar": null,
   "bio": "مسؤول خدم ليو جانغ ثم ليو باي، وساعده على مكافأة أتباعه من الخزينة دون أن يفقرها.",
   "at": "cand",
   "aff": "shu",
   "from": 214,
   "to": 222,
   "died": 222
  },
  {
   "n": "تساو تساو",
   "trait": "tactician",
   "flaw": "harsh",
   "lead": 5,
   "fame": 70,
   "src": "hist",
   "wiki": "Cao_Cao",
   "ar": "تساو تساو",
   "bio": "رجل دولة وأمير حرب وشاعر، أحكم قبضته على بلاط هان في سنواتها الأخيرة ووضع أساس دولة وي.",
   "born": 155,
   "at": "wei",
   "ruler": true,
   "died": 220
  },
  {
   "n": "شياهو دون",
   "trait": "brave",
   "flaw": "reckless",
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Xiahou_Dun",
   "ar": null,
   "bio": "من قادة تساو تساو وسياسييه، وخدم أشهراً قليلة في عهد خليفته قبل وفاته سنة 220.",
   "at": "wei",
   "died": 220
  },
  {
   "n": "شياهو يوان",
   "trait": "swift",
   "flaw": "reckless",
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Xiahou_Yuan",
   "ar": null,
   "bio": "قائد في خدمة تساو تساو، عُرف بحملاته في غرب الصين، وقُتل في معركة جبل دينغجون سنة 219.",
   "at": "wei",
   "died": 219
  },
  {
   "n": "جانغ لياو",
   "trait": "cavalier",
   "flaw": null,
   "lead": 4,
   "fame": 30,
   "src": "hist",
   "wiki": "Zhang_Liao",
   "ar": null,
   "bio": "قائد في خدمة تساو تساو، ذاع صيته بدفاعه عن خفي في معركة معبر شياوياو.",
   "born": 169,
   "at": "wei",
   "died": 222
  },
  {
   "n": "سيما يي",
   "trait": "defender",
   "flaw": "disloyal",
   "lead": 4,
   "fame": 30,
   "src": "hist",
   "wiki": "Sima_Yi",
   "ar": "سيما يي",
   "bio": "قائد وسياسي ثم وصي على دولة وي. بدأ مسيرته الرسمية في عهد تساو تساو.",
   "born": 179,
   "at": "cand",
   "aff": "wei",
   "from": 208,
   "to": 251,
   "died": 251
  },
  {
   "n": "تساو رن",
   "trait": "defender",
   "flaw": null,
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Cao_Ren",
   "ar": null,
   "bio": "ابن عم تساو تساو ومن كبار قادته، وواصل الخدمة في دولة وي حتى وفاته سنة 223.",
   "born": 168,
   "at": "wei",
   "died": 223
  },
  {
   "n": "شو هوانغ",
   "trait": "siege",
   "flaw": null,
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Xu_Huang",
   "ar": null,
   "bio": "قائد في خدمة تساو تساو ثم في دولة وي حتى وفاته سنة 227.",
   "at": "wei",
   "died": 227
  },
  {
   "n": "جانغ خه",
   "trait": "mountaineer",
   "flaw": null,
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Zhang_He",
   "ar": "تشانغ هي (ضابط)",
   "bio": "قائد في خدمة تساو تساو، واستمر في دولة وي في عهد أول حاكمين لها.",
   "at": "cand",
   "aff": "wei",
   "from": 208,
   "to": 231,
   "died": 231
  },
  {
   "n": "تساو تشون",
   "trait": "elite",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Cao_Chun",
   "ar": null,
   "bio": "ابن عم تساو تساو، اشتهر بقيادة فرسان «النمر والفهد».",
   "born": 170,
   "at": "cand",
   "aff": "wei",
   "from": 208,
   "to": 210,
   "died": 210
  },
  {
   "n": "شون يو",
   "trait": "merchant",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Xun_Yu",
   "ar": null,
   "bio": "مستشار تساو تساو ومن أبرز رجال إدارته.",
   "born": 163,
   "at": "cand",
   "aff": "wei",
   "from": 208,
   "to": 212,
   "died": 212
  },
  {
   "n": "يو جين",
   "trait": "logistician",
   "flaw": "disloyal",
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Yu_Jin",
   "ar": null,
   "bio": "انضم إلى تساو تساو سنة 192 مع بداية الحروب الأهلية وصار من قادته.",
   "at": "cand",
   "aff": "wei",
   "from": 208,
   "to": 221,
   "died": 221
  },
  {
   "n": "شو تشو",
   "trait": "brave",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Xu_Chu",
   "ar": null,
   "bio": "بدأ حارساً شخصياً لتساو تساو ثم صار قائداً في وي. لقّبه رجاله «النمر الأحمق» لقوته وبساطته.",
   "at": "cand",
   "aff": "wei",
   "from": 208,
   "to": 230,
   "died": 230
  },
  {
   "n": "دنغ آي",
   "trait": "mountaineer",
   "flaw": "cautious",
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Deng_Ai",
   "ar": null,
   "bio": "قائد وسياسي في وي، اشتهر بدوره الحاسم في غزو وي لشو.",
   "born": 197,
   "at": "cand",
   "aff": "wei",
   "from": 230,
   "to": 264,
   "died": 264
  },
  {
   "n": "بانغ دي",
   "trait": "brave",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Pang_De",
   "ar": null,
   "bio": "بدأ في خدمة ما تنغ ثم ابنه ما تشاو، وبقي في هانزونغ حين انتقل ما تشاو إلى ليو باي.",
   "at": "cand",
   "from": 211,
   "to": 219,
   "died": 219
  },
  {
   "n": "تساو جانغ",
   "trait": "cavalier",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Cao_Zhang",
   "ar": null,
   "bio": "ابن تساو تساو الملقب «ذو اللحية الصفراء»، قاد جنده إلى انتصارات على غارات الووهوان في الشمال.",
   "at": "cand",
   "aff": "wei",
   "from": 216,
   "to": 223,
   "died": 223
  },
  {
   "n": "تساو شيو",
   "trait": "swift",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Cao_Xiu",
   "ar": null,
   "bio": "قريب بعيد لتساو تساو، تفوّق على جانغ في في بداية حملة هانزونغ، ومات بعد هزيمة وي في معركة شيتينغ سنة 228.",
   "at": "cand",
   "aff": "wei",
   "from": 217,
   "to": 228,
   "died": 228
  },
  {
   "n": "شو شو",
   "trait": "tactician",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Xu_Shu",
   "ar": null,
   "bio": "كان في شبابه مقاتلاً يأخذ الحق بيده، ثم خدم ليو باي قبل أن ينتقل إلى معسكر تساو تساو.",
   "at": "cand",
   "from": 208,
   "to": 234,
   "died": 234
  },
  {
   "n": "لي ديان",
   "trait": "defender",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Li_Dian",
   "ar": "لي ديان",
   "bio": "قائد وسياسي في خدمة تساو تساو، شارك في معركة غواندو سنة 200.",
   "at": "cand",
   "aff": "wei",
   "from": 200,
   "to": 217,
   "died": 217
  },
  {
   "n": "مان تشونغ",
   "trait": "defender",
   "flaw": null,
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Man_Chong",
   "ar": null,
   "bio": "قائد وسياسي خدم تساو تساو ثم دولة وي من بعده.",
   "at": "cand",
   "aff": "wei",
   "from": 208,
   "to": 242,
   "died": 242
  },
  {
   "n": "سون تشوان",
   "trait": "merchant",
   "flaw": "cautious",
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Sun_Quan",
   "ar": "سون تشوان",
   "bio": "مؤسس وو الشرقية، ورث السلطة التي أقامها أبوه سون جيان وأخوه سون تسه.",
   "born": 182,
   "at": "wu",
   "ruler": true,
   "died": 252
  },
  {
   "n": "جو يو",
   "trait": "naval",
   "flaw": null,
   "lead": 4,
   "fame": 70,
   "src": "hist",
   "wiki": "Zhou_Yu",
   "ar": null,
   "bio": "خدم سون تسه ثم سون تشوان، وأدّى دوراً قيادياً في هزيمة تساو تساو في معركة المنحدرات الحمراء.",
   "born": 175,
   "at": "wu",
   "died": 210
  },
  {
   "n": "لو منغ",
   "trait": "tactician",
   "flaw": null,
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Lü_Meng",
   "ar": null,
   "bio": "قائد وسياسي في خدمة سون تشوان، قاد غزو إقليم جينغ سنة 219.",
   "born": 178,
   "at": "wu",
   "died": 220
  },
  {
   "n": "غان نينغ",
   "trait": "elite",
   "flaw": "reckless",
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Gan_Ning",
   "ar": "غان نينغ",
   "bio": "كان قرصاناً سيئ السمعة، ثم ترك حياة النهب وصار قائداً في خدمة سون تشوان.",
   "at": "wu",
   "died": 220
  },
  {
   "n": "تشنغ بو",
   "trait": "defender",
   "flaw": null,
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Cheng_Pu",
   "ar": null,
   "bio": "قائد مخضرم خدم سون جيان ثم سون تسه ثم سون تشوان.",
   "at": "cand",
   "aff": "wu",
   "from": 208,
   "to": 210,
   "died": 210
  },
  {
   "n": "هان دانغ",
   "trait": "archer",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Han_Dang",
   "ar": null,
   "bio": "خدم سون جيان وسون تسه ثم سون تشوان، وعاش حتى أوائل عصر الممالك الثلاث.",
   "at": "cand",
   "aff": "wu",
   "from": 208,
   "to": 227,
   "died": 227
  },
  {
   "n": "هوانغ غاي",
   "trait": "naval",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Huang_Gai",
   "ar": null,
   "bio": "قائد خدم سون جيان وسون تسه ثم سون تشوان.",
   "at": "wu",
   "died": 215
  },
  {
   "n": "لينغ تونغ",
   "trait": "brave",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Ling_Tong",
   "ar": "لينغ تونغ",
   "bio": "دخل خدمة سون تشوان وهو فتى، ومات سنة 217.",
   "born": 189,
   "at": "cand",
   "aff": "wu",
   "from": 208,
   "to": 217,
   "died": 217
  },
  {
   "n": "لو سو",
   "trait": "logistician",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Lu_Su",
   "ar": null,
   "bio": "قائد وسياسي، انضم إلى سون تشوان سنة 200 حين تسلّم السلطة.",
   "born": 172,
   "at": "wu",
   "died": 217
  },
  {
   "n": "جو تاي",
   "trait": "defender",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Zhou_Tai",
   "ar": null,
   "bio": "خدم سون تسه ثم سون تشوان، وعاش حتى أوائل عصر الممالك الثلاث.",
   "at": "cand",
   "aff": "wu",
   "from": 208,
   "to": 223,
   "died": 223
  },
  {
   "n": "جيانغ تشين",
   "trait": "naval",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Jiang_Qin",
   "ar": null,
   "bio": "قائد وخبير بحري خدم سون تسه ثم سون تشوان، وشارك في معركة معبر شياوياو.",
   "at": "cand",
   "aff": "wu",
   "from": 208,
   "to": 220,
   "died": 220
  },
  {
   "n": "جو هوان",
   "trait": "siege",
   "flaw": "arrogant",
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Zhu_Huan",
   "ar": null,
   "bio": "بدأ مبكراً في خدمة سون تشوان، لكنه لم ينل قيادة مهمة إلا متأخراً.",
   "born": 177,
   "at": "cand",
   "aff": "wu",
   "from": 208,
   "to": 238,
   "died": 238
  },
  {
   "n": "لو شون",
   "trait": "defender",
   "flaw": null,
   "lead": 4,
   "fame": 30,
   "src": "hist",
   "wiki": "Lu_Xun_(Eastern_Wu)",
   "ar": null,
   "bio": "بدأ موظفاً عند سون تشوان، وساعد لو منغ في غزو جينغ سنة 219، وصار لاحقاً مستشاراً إمبراطورياً لوو.",
   "born": 183,
   "at": "cand",
   "aff": "wu",
   "from": 215,
   "to": 245,
   "died": 245
  },
  {
   "n": "جو ران",
   "trait": "defender",
   "flaw": null,
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Zhu_Ran",
   "ar": null,
   "bio": "صديق طفولة سون تشوان. ساعد في أسر قوان يو سنة 219، ودافع عن جيانغلينغ بخمسة آلاف رجل أمام جيش يفوقه عشر مرات.",
   "born": 182,
   "at": "cand",
   "aff": "wu",
   "from": 212,
   "to": 249,
   "died": 249
  },
  {
   "n": "شو شنغ",
   "trait": "naval",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Xu_Sheng",
   "ar": null,
   "bio": "قائد في خدمة سون تشوان في أواخر هان وأوائل الممالك الثلاث.",
   "at": "cand",
   "aff": "wu",
   "from": 208,
   "to": 229,
   "died": 229
  },
  {
   "n": "دينغ فنغ",
   "trait": "swift",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Ding_Feng_(general)",
   "ar": null,
   "bio": "قائد وسياسي في دولة وو الشرقية، مات سنة 271.",
   "at": "cand",
   "aff": "wu",
   "from": 222,
   "to": 271,
   "died": 271
  },
  {
   "n": "جانغ لو",
   "trait": "defender",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Zhang_Lu_(Han_dynasty)",
   "ar": null,
   "bio": "زعيم ديني وأمير حرب، ثالث «المعلمين السماويين» الطاويين. حكم هانزونغ حتى استسلم لتساو تساو سنة 215.",
   "at": "neutral",
   "died": 216
  },
  {
   "n": "منغ هوو",
   "trait": "brave",
   "flaw": "reckless",
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Meng_Huo",
   "ar": null,
   "bio": "زعيم محلي في منطقة نانجونغ. معظم ما يُروى عنه يأتي من مصادر متأخرة ومن الرواية الشعبية.",
   "at": "neutral",
   "died": 230
  },
  {
   "n": "شي شيه",
   "trait": "merchant",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Shi_Xie",
   "ar": null,
   "bio": "قائد وسياسي وأمير حرب حكم جياوتشو (شمال فيتنام اليوم) في أواخر هان وأوائل الممالك الثلاث.",
   "born": 137,
   "at": "neutral",
   "died": 226
  },
  {
   "n": "هان سوي",
   "trait": "desert",
   "flaw": "disloyal",
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Han_Sui",
   "ar": null,
   "bio": "قائد وأمير حرب صغير، نشط معظم حياته في إقليم ليانغ الشمالي الغربي.",
   "at": "neutral",
   "died": 215
  },
  {
   "n": "ما تنغ",
   "trait": "cavalier",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Ma_Teng",
   "ar": null,
   "bio": "قائد وأمير حرب سيطر على إقليم ليانغ، وأبو ما تشاو.",
   "at": "neutral",
   "died": 212
  },
  {
   "n": "كبي نينغ",
   "trait": "cavalier",
   "flaw": null,
   "lead": 4,
   "fame": 30,
   "src": "hist",
   "wiki": "Kebineng",
   "ar": null,
   "bio": "زعيم من الشيانبي صعد نجمه بعد أن هزم تساو تساو الووهوان سنة 207، واغتالته قوات وي سنة 235.",
   "at": "event",
   "died": 235
  },
  {
   "n": "بو دو غن",
   "trait": "swift",
   "flaw": "harsh",
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Budugen",
   "ar": null,
   "bio": "زعيم من الشيانبي وحفيد تانشيهواي، حفظ استقلاله بإعلان الولاء لوي وإرسال الجزية.",
   "at": "event",
   "died": 233
  },
  {
   "n": "سو لي",
   "trait": "archer",
   "flaw": null,
   "lead": 2,
   "fame": 0,
   "src": "fic",
   "wiki": null,
   "ar": null,
   "bio": "شخصية متخيَّلة من صنع اللعبة، لا تستند إلى سيرة تاريخية.",
   "at": "event"
  },
  {
   "n": "مولو ملك الوحوش",
   "trait": "brave",
   "flaw": "reckless",
   "lead": 2,
   "fame": 8,
   "src": "novel",
   "wiki": "List_of_fictional_people_of_the_Three_Kingdoms",
   "ar": null,
   "bio": "شخصية من رواية «الممالك الثلاث» التي كُتبت في القرن الرابع عشر، ولا ذكر لها في السجلات التاريخية.",
   "at": "event"
  },
  {
   "n": "وو تو قو",
   "trait": "defender",
   "flaw": null,
   "lead": 3,
   "fame": 8,
   "src": "novel",
   "wiki": "List_of_fictional_people_of_the_Three_Kingdoms",
   "ar": null,
   "bio": "شخصية من رواية «الممالك الثلاث» التي كُتبت في القرن الرابع عشر، ولا ذكر لها في السجلات التاريخية.",
   "at": "event"
  },
  {
   "n": "تشو رونغ",
   "trait": "swift",
   "flaw": null,
   "lead": 2,
   "fame": 8,
   "src": "novel",
   "wiki": "List_of_fictional_people_of_the_Three_Kingdoms",
   "ar": null,
   "bio": "شخصية من رواية «الممالك الثلاث» التي كُتبت في القرن الرابع عشر، ولا ذكر لها في السجلات التاريخية.",
   "at": "event"
  },
  {
   "n": "يو فو لوو",
   "trait": "mountaineer",
   "flaw": null,
   "lead": 2,
   "fame": 0,
   "src": "fic",
   "wiki": null,
   "ar": null,
   "bio": "شخصية متخيَّلة من صنع اللعبة، لا تستند إلى سيرة تاريخية.",
   "at": "event"
  },
  {
   "n": "تشين دا",
   "trait": "swift",
   "flaw": "greedy",
   "lead": 2,
   "fame": 0,
   "src": "fic",
   "wiki": null,
   "ar": null,
   "bio": "شخصية متخيَّلة من صنع اللعبة، لا تستند إلى سيرة تاريخية.",
   "at": "event"
  },
  {
   "n": "لوو هاي",
   "trait": "naval",
   "flaw": "greedy",
   "lead": 2,
   "fame": 0,
   "src": "fic",
   "wiki": null,
   "ar": null,
   "bio": "شخصية متخيَّلة من صنع اللعبة، لا تستند إلى سيرة تاريخية.",
   "at": "event"
  }
 ],
 "umayyad": [
  {
   "n": "سليمان بن عبد الملك",
   "trait": "merchant",
   "flaw": "greedy",
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Sulayman_ibn_Abd_al-Malik",
   "ar": "سليمان بن عبد الملك",
   "bio": "الخليفة الأموي السابع (715 إلى 717)، ابن الخليفة عبد الملك. كان والياً على فلسطين قبل الخلافة.",
   "born": 674,
   "at": "umayyad",
   "ruler": true,
   "died": 717
  },
  {
   "n": "مسلمة بن عبد الملك",
   "trait": "siege",
   "flaw": null,
   "lead": 4,
   "fame": 70,
   "src": "hist",
   "wiki": "Maslama_ibn_Abd_al-Malik",
   "ar": "مسلمة بن عبد الملك",
   "bio": "أمير أموي ومن أبرز قادة العرب في مطلع القرن الثامن، قاد حملات على الروم والخزر.",
   "at": "umayyad",
   "died": 738
  },
  {
   "n": "العباس بن الوليد",
   "trait": "cavalier",
   "flaw": null,
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Al-Abbas_ibn_al-Walid",
   "ar": "العباس بن الوليد بن عبد الملك",
   "bio": "أمير وقائد أموي، أكبر أبناء الخليفة الوليد الأول، وبرز قائداً في الحروب مع الروم.",
   "at": "umayyad",
   "died": 750
  },
  {
   "n": "الجراح الحكمي",
   "trait": "brave",
   "flaw": "reckless",
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Al-Jarrah_ibn_Abdallah_al-Hakami",
   "ar": "الجراح الحكمي",
   "bio": "نبيل وقائد عربي من قبيلة حكم، برز في الحروب الأموية مطلع القرن الثامن.",
   "at": "umayyad",
   "died": 730
  },
  {
   "n": "محمد بن مروان",
   "trait": "defender",
   "flaw": null,
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Muhammad_ibn_Marwan",
   "ar": "محمد بن مروان",
   "bio": "أمير أموي ومن أهم قادة الدولة بين 690 و710، ومات نحو سنة 720.",
   "at": "umayyad",
   "died": 720
  },
  {
   "n": "عمر بن هبيرة",
   "trait": "naval",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Umar_ibn_Hubayra",
   "ar": "عمر بن هبيرة",
   "bio": "قائد أموي بارز صار والياً على العراق، وأدى دوراً في صراع القيسية واليمنية.",
   "at": "umayyad",
   "died": 726
  },
  {
   "n": "سعيد الحرشي",
   "trait": "swift",
   "flaw": "harsh",
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Sa'id_ibn_Amr_al-Harashi",
   "ar": "سعيد بن عمرو الحرشي",
   "bio": "قائد ووالٍ أموي بارز، أدى دوراً مهماً في الحروب العربية الخزرية.",
   "at": "cand",
   "aff": "umayyad",
   "from": 715,
   "to": 735,
   "died": 735
  },
  {
   "n": "مروان بن محمد",
   "trait": "tactician",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Marwan_II",
   "ar": "مروان بن محمد",
   "bio": "آخر خلفاء بني أمية (744 إلى 750). قبل الخلافة قاد جبهة القوقاز وهزم الخزر سنة 737.",
   "born": 691,
   "at": "cand",
   "aff": "umayyad",
   "from": 715,
   "to": 750,
   "died": 750
  },
  {
   "n": "بشر بن الوليد",
   "trait": "archer",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Bishr_ibn_al-Walid",
   "ar": "بشر بن الوليد بن عبد الملك",
   "bio": "أمير وقائد أموي، قاد غزوتين على الروم سنة 710 و714.",
   "at": "cand",
   "aff": "umayyad",
   "from": 715,
   "to": 745,
   "died": 745
  },
  {
   "n": "خالد القسري",
   "trait": "merchant",
   "flaw": "greedy",
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Khalid_al-Qasri",
   "ar": "خالد القسري",
   "bio": "والي مكة ثم والي العراق من 724 إلى 738، وكان منصبه من أرفع مناصب الدولة وأغناها.",
   "at": "cand",
   "aff": "umayyad",
   "from": 715,
   "to": 743,
   "died": 743
  },
  {
   "n": "سليمان بن معاذ",
   "trait": "defender",
   "flaw": null,
   "lead": 2,
   "fame": 8,
   "src": "hist",
   "wiki": "Siege_of_Constantinople_(717–718)",
   "ar": null,
   "bio": "يرد اسمه في روايات حصار القسطنطينية (717 إلى 718) قائداً في الجيش الأموي. لا سيرة مستقلة له في ويكيبيديا.",
   "at": "cand",
   "aff": "umayyad",
   "from": 715,
   "to": 720,
   "died": 720
  },
  {
   "n": "يزيد بن المهلب",
   "trait": "logistician",
   "flaw": "disloyal",
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Yazid_ibn_al-Muhallab",
   "ar": "يزيد بن المهلب",
   "bio": "قائد ورجل دولة أموي في العراق وخراسان، ثار على الدولة سنة 720.",
   "born": 672,
   "at": "cand",
   "aff": "umayyad",
   "from": 715,
   "to": 720,
   "died": 720
  },
  {
   "n": "هشام بن عبد الملك",
   "trait": "elite",
   "flaw": "cautious",
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Hisham_ibn_Abd_al-Malik",
   "ar": "هشام بن عبد الملك",
   "bio": "الخليفة الأموي العاشر، حكم من 724 حتى وفاته سنة 743.",
   "born": 691,
   "at": "cand",
   "aff": "umayyad",
   "from": 715,
   "to": 743,
   "died": 743
  },
  {
   "n": "عبد الله البطال",
   "trait": "brave",
   "flaw": null,
   "lead": 3,
   "fame": 70,
   "src": "hist",
   "wiki": "Abdallah_al-Battal",
   "ar": "عبد الله البطال",
   "bio": "قائد في الحروب العربية البيزنطية مطلع القرن الثامن. أخباره الموثقة قليلة، ونشأت حوله بعد موته سيرة شعبية واسعة في الأناضول.",
   "at": "cand",
   "aff": "umayyad",
   "from": 715,
   "to": 740,
   "died": 740
  },
  {
   "n": "نصر بن سيار",
   "trait": "defender",
   "flaw": null,
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Nasr_ibn_Sayyar",
   "ar": "نصر بن سيار الكناني",
   "bio": "قائد عربي وآخر ولاة بني أمية على خراسان (738 إلى 748)، وبرز في الحروب ضد الترغش.",
   "born": 663,
   "at": "cand",
   "aff": "umayyad",
   "from": 715,
   "to": 748,
   "died": 748
  },
  {
   "n": "أسد بن عبد الله القسري",
   "trait": "cavalier",
   "flaw": "harsh",
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Asad_ibn_Abdallah_al-Qasri",
   "ar": "أسد بن عبد الله القسري",
   "bio": "والي خراسان مرتين في عهد الخليفة هشام بن عبد الملك.",
   "at": "cand",
   "aff": "umayyad",
   "from": 723,
   "to": 738,
   "died": 738
  },
  {
   "n": "الحارث بن سريج",
   "trait": "swift",
   "flaw": "disloyal",
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Al-Harith_ibn_Surayj",
   "ar": "الحارث بن سريج",
   "bio": "قائد ثورة اجتماعية واسعة على الدولة الأموية في خراسان.",
   "at": "cand",
   "from": 728,
   "to": 746,
   "died": 746
  },
  {
   "n": "مسلم بن سعيد الكلابي",
   "trait": "tactician",
   "flaw": "cautious",
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Muslim_ibn_Sa'id_al-Kilabi",
   "ar": "مسلم بن سعيد الكلابي",
   "bio": "والي خراسان (723 إلى 724). عُرف بمحاولته استمالة أهل ما وراء النهر، وبهزيمته الكبيرة في «يوم العطش» أمام الترغش.",
   "at": "cand",
   "aff": "umayyad",
   "from": 720,
   "to": 735,
   "died": 735
  },
  {
   "n": "إسحاق بن مسلم العقيلي",
   "trait": "mountaineer",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Ishaq_ibn_Muslim_al-Uqayli",
   "ar": "إسحاق بن مسلم العقيلي",
   "bio": "قائد ووالٍ أموي على أرمينية، ومن أقرب أنصار مروان بن محمد.",
   "at": "cand",
   "aff": "umayyad",
   "from": 730,
   "to": 760,
   "died": 760
  },
  {
   "n": "مسلمة بن هشام",
   "trait": "siege",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Maslama_ibn_Hisham",
   "ar": "مسلمة بن هشام",
   "bio": "أمير وقائد أموي. كان استيلاؤه على أنقرة سنة 739 آخر مكاسب الأمويين في حروبهم مع الروم.",
   "at": "cand",
   "aff": "umayyad",
   "from": 735,
   "to": 750,
   "died": 750
  },
  {
   "n": "ثيودوسيوس",
   "trait": "merchant",
   "flaw": "cautious",
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Theodosius_III",
   "ar": "ثيودوسيوس الثالث",
   "bio": "إمبراطور الروم من نحو 715 إلى 717. كان جابي ضرائب في أدراميتيون قبل أن يُرفع إلى العرش.",
   "at": "byzantine",
   "ruler": true,
   "died": 754
  },
  {
   "n": "ليون الإيساوري",
   "trait": "defender",
   "flaw": null,
   "lead": 5,
   "fame": 70,
   "src": "hist",
   "wiki": "Leo_III_the_Isaurian",
   "ar": "لاون الثالث الإيساوري",
   "bio": "قائد رومي صار إمبراطوراً سنة 717 وأسس الأسرة الإيساورية، وحكم حتى وفاته سنة 741.",
   "born": 685,
   "at": "byzantine",
   "died": 741
  },
  {
   "n": "أرتاباسدوس",
   "trait": "cavalier",
   "flaw": "disloyal",
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Artabasdos",
   "ar": "أرتاباسدوس",
   "bio": "قائد رومي من أصل أرمني، استولى على العرش بين 741 و743.",
   "at": "byzantine",
   "died": 743
  },
  {
   "n": "سيسينيوس",
   "trait": "brave",
   "flaw": null,
   "lead": 2,
   "fame": 8,
   "src": "hist",
   "wiki": "Rendakis",
   "ar": null,
   "bio": "من أسرة رينداكيس النبيلة القوية في الدولة الرومية بين القرنين الثامن والعاشر.",
   "at": "byzantine",
   "died": 719
  },
  {
   "n": "باسيل أونوماغولوس",
   "trait": "logistician",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Basil_Onomagoulos",
   "ar": null,
   "bio": "موظف رومي أُعلن إمبراطوراً منافساً في صقلية سنة 717 باسم طيباريوس.",
   "at": "byzantine",
   "died": 718
  },
  {
   "n": "نقيطاس",
   "trait": "swift",
   "flaw": null,
   "lead": 2,
   "fame": 0,
   "src": "fic",
   "wiki": null,
   "ar": null,
   "bio": "شخصية متخيَّلة من صنع اللعبة، لا تستند إلى سيرة تاريخية.",
   "at": "cand",
   "aff": "byzantine",
   "from": 715,
   "to": 775
  },
  {
   "n": "مانويل",
   "trait": "elite",
   "flaw": null,
   "lead": 3,
   "fame": 0,
   "src": "fic",
   "wiki": null,
   "ar": null,
   "bio": "شخصية متخيَّلة من صنع اللعبة، لا تستند إلى سيرة تاريخية.",
   "at": "cand",
   "aff": "byzantine",
   "from": 715,
   "to": 775
  },
  {
   "n": "بطرس",
   "trait": "mountaineer",
   "flaw": null,
   "lead": 2,
   "fame": 0,
   "src": "fic",
   "wiki": null,
   "ar": null,
   "bio": "شخصية متخيَّلة من صنع اللعبة، لا تستند إلى سيرة تاريخية.",
   "at": "cand",
   "aff": "byzantine",
   "from": 715,
   "to": 775
  },
  {
   "n": "ثيوفيلاكتوس",
   "trait": "siege",
   "flaw": null,
   "lead": 2,
   "fame": 0,
   "src": "fic",
   "wiki": null,
   "ar": null,
   "bio": "شخصية متخيَّلة من صنع اللعبة، لا تستند إلى سيرة تاريخية.",
   "at": "cand",
   "aff": "byzantine",
   "from": 715,
   "to": 775
  },
  {
   "n": "يوحنا",
   "trait": "archer",
   "flaw": null,
   "lead": 2,
   "fame": 0,
   "src": "fic",
   "wiki": null,
   "ar": null,
   "bio": "شخصية متخيَّلة من صنع اللعبة، لا تستند إلى سيرة تاريخية.",
   "at": "cand",
   "aff": "byzantine",
   "from": 715,
   "to": 775
  },
  {
   "n": "ميخائيل",
   "trait": "naval",
   "flaw": "greedy",
   "lead": 2,
   "fame": 0,
   "src": "fic",
   "wiki": null,
   "ar": null,
   "bio": "شخصية متخيَّلة من صنع اللعبة، لا تستند إلى سيرة تاريخية.",
   "at": "cand",
   "aff": "byzantine",
   "from": 715,
   "to": 775
  },
  {
   "n": "أناستاسيوس",
   "trait": "naval",
   "flaw": null,
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Anastasius_II_(emperor)",
   "ar": "أرتيميوس أناستاسيوس الثاني",
   "bio": "إمبراطور الروم من 713 إلى 715، واسمه الأصلي أرتيميوس. خُلع سنة 715 ومات سنة 719.",
   "at": "cand",
   "aff": "byzantine",
   "from": 715,
   "to": 719,
   "died": 719
  },
  {
   "n": "قسطنطين",
   "trait": "tactician",
   "flaw": "harsh",
   "lead": 4,
   "fame": 30,
   "src": "hist",
   "wiki": "Constantine_V",
   "ar": "قسطنطين الخامس",
   "bio": "ابن ليون الثالث، وُلد سنة 718 وحكم إمبراطوراً من 741 إلى 775، وكان قائداً عسكرياً قديراً.",
   "born": 718,
   "at": "cand",
   "aff": "byzantine",
   "from": 736,
   "to": 775,
   "died": 775
  },
  {
   "n": "بارجيك",
   "trait": "cavalier",
   "flaw": "reckless",
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Barjik",
   "ar": "بارجيك",
   "bio": "خاقان خزري قاد جيوش الخزر في الحروب العربية الخزرية، ولقّبه أعداؤه «الخاقان الملعون». مات سنة 731 أو 732.",
   "at": "khazar",
   "died": 731
  },
  {
   "n": "آلب طرخان",
   "trait": "archer",
   "flaw": null,
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Alp_Tarkhan",
   "ar": null,
   "bio": "قائد خزري في الحروب العربية الخزرية. لا يُعرف إن كان «آلب طرخان» اسماً أم لقباً، فآلب تعني البطل وطرخان تعني أمير الحرب.",
   "at": "khazar",
   "died": 737
  },
  {
   "n": "هزر طرخان",
   "trait": "brave",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Hazer_Tarkhan",
   "ar": "هزر طرخان",
   "bio": "قائد خزري قاد سنة 737 جيشاً في مواجهة مروان بن محمد.",
   "alias": [
    "هزار طرخان"
   ],
   "at": "cand",
   "aff": "khazar",
   "from": 715,
   "to": 737,
   "died": 737
  },
  {
   "n": "بولان",
   "trait": "merchant",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Bulan_(Khazar)",
   "ar": "بولان (خزر)",
   "bio": "حاكم خزري ومؤسس السلالة البولانية، ويُنسب إليه عادةً قيادة تحوّل الخزر إلى اليهودية.",
   "at": "khazar",
   "died": 760
  },
  {
   "n": "قاطون",
   "trait": "swift",
   "flaw": "harsh",
   "lead": 2,
   "fame": 0,
   "src": "fic",
   "wiki": null,
   "ar": null,
   "bio": "شخصية متخيَّلة من صنع اللعبة، لا تستند إلى سيرة تاريخية.",
   "at": "cand",
   "aff": "khazar",
   "from": 715,
   "to": 775
  },
  {
   "n": "قوتلوغ",
   "trait": "elite",
   "flaw": null,
   "lead": 2,
   "fame": 0,
   "src": "fic",
   "wiki": null,
   "ar": null,
   "bio": "شخصية متخيَّلة من صنع اللعبة، لا تستند إلى سيرة تاريخية.",
   "at": "cand",
   "aff": "khazar",
   "from": 715,
   "to": 775
  },
  {
   "n": "تونغا",
   "trait": "tactician",
   "flaw": "arrogant",
   "lead": 2,
   "fame": 0,
   "src": "fic",
   "wiki": null,
   "ar": null,
   "bio": "شخصية متخيَّلة من صنع اللعبة، لا تستند إلى سيرة تاريخية.",
   "at": "cand",
   "aff": "khazar",
   "from": 715,
   "to": 775
  },
  {
   "n": "قرلغ",
   "trait": "mountaineer",
   "flaw": null,
   "lead": 2,
   "fame": 0,
   "src": "fic",
   "wiki": null,
   "ar": null,
   "bio": "شخصية متخيَّلة من صنع اللعبة، لا تستند إلى سيرة تاريخية.",
   "at": "cand",
   "aff": "khazar",
   "from": 715,
   "to": 775
  },
  {
   "n": "ساروخ",
   "trait": "logistician",
   "flaw": null,
   "lead": 2,
   "fame": 0,
   "src": "fic",
   "wiki": null,
   "ar": null,
   "bio": "شخصية متخيَّلة من صنع اللعبة، لا تستند إلى سيرة تاريخية.",
   "at": "cand",
   "aff": "khazar",
   "from": 715,
   "to": 775
  },
  {
   "n": "باغاتور",
   "trait": "desert",
   "flaw": null,
   "lead": 2,
   "fame": 0,
   "src": "fic",
   "wiki": null,
   "ar": null,
   "bio": "شخصية متخيَّلة من صنع اللعبة، لا تستند إلى سيرة تاريخية.",
   "at": "cand",
   "aff": "khazar",
   "from": 715,
   "to": 775
  },
  {
   "n": "بيهار",
   "trait": "cavalier",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Bihar_(Khazar)",
   "ar": "بهار (خزر)",
   "bio": "خاقان الخزر في ثلاثينيات القرن الثامن، وربما هو «بوسير إرباس» المذكور في المصادر الرومية.",
   "alias": [
    "الخاقان بيهار"
   ],
   "at": "cand",
   "aff": "khazar",
   "from": 730,
   "to": 750,
   "died": 750
  },
  {
   "n": "سمبات الباغراتي",
   "trait": "cavalier",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Smbat_VI_Bagratuni",
   "ar": null,
   "bio": "أمير أرمني من الأسرة الباغراتية، كان الأمير الحاكم لأرمينية بانقطاعات من 691 حتى العقد الثاني من القرن الثامن.",
   "alias": [
    "سمبات"
   ],
   "at": "neutral",
   "died": 726
  },
  {
   "n": "غوارام الكرجي",
   "trait": "mountaineer",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Guaram_III_of_Iberia",
   "ar": null,
   "bio": "أمير حاكم لإيبيريا (كارتلي، شرق جورجيا) من قبل 693 إلى نحو 748، وحمل لقب «كوروبالاتيس» الرومي.",
   "at": "neutral",
   "died": 748
  },
  {
   "n": "حسّان التدمري",
   "trait": "desert",
   "flaw": null,
   "lead": 2,
   "fame": 0,
   "src": "fic",
   "wiki": null,
   "ar": null,
   "bio": "شخصية متخيَّلة من صنع اللعبة، لا تستند إلى سيرة تاريخية.",
   "at": "neutral"
  },
  {
   "n": "أشوط الباغراتي",
   "trait": "defender",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Ashot_III_Bagratuni",
   "ar": null,
   "bio": "أمير أرمينية من 732 إلى 748، ويُعرف بأشوط الأعمى. عيّنه مروان بن محمد، وانتهج سياسة التقارب مع العرب.",
   "born": 690,
   "alias": [
    "أشوط الأرمني"
   ],
   "at": "cand",
   "from": 732,
   "to": 748,
   "died": 748
  },
  {
   "n": "سولوك أبو مزاحم",
   "trait": "cavalier",
   "flaw": null,
   "lead": 4,
   "fame": 30,
   "src": "hist",
   "wiki": "Suluk_(Türgesh_khagan)",
   "ar": null,
   "bio": "خاقان الترغش الذي قاتل الأمويين في ما وراء النهر، وسمّته المصادر العربية «أبا مزاحم». قُتل سنة 738.",
   "at": "event",
   "died": 738
  },
  {
   "n": "كورصول",
   "trait": "swift",
   "flaw": "reckless",
   "lead": 3,
   "fame": 30,
   "src": "hist",
   "wiki": "Kül-chor",
   "ar": "كورصول",
   "bio": "من كبار قادة الترغش في عهد الخاقان سولوك، ويُعرف في المصادر الصينية باسم «باغا طرخان». قتل سولوك سنة 738.",
   "at": "event",
   "died": 740
  },
  {
   "n": "يلدوز طرخان",
   "trait": "archer",
   "flaw": null,
   "lead": 2,
   "fame": 0,
   "src": "fic",
   "wiki": null,
   "ar": null,
   "bio": "شخصية متخيَّلة من صنع اللعبة، لا تستند إلى سيرة تاريخية.",
   "at": "event"
  },
  {
   "n": "ترفل خان",
   "trait": "cavalier",
   "flaw": null,
   "lead": 4,
   "fame": 30,
   "src": "hist",
   "wiki": "Tervel_of_Bulgaria",
   "ar": "تيرفيل ملك بلغاريا",
   "bio": "حاكم بلغاريا مطلع القرن الثامن، ومنحه الإمبراطور جستنيان الثاني لقب «قيصر» سنة 705.",
   "at": "event",
   "died": 721
  },
  {
   "n": "كورميسوش",
   "trait": "brave",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Kormisosh",
   "ar": null,
   "bio": "حاكم لبلغاريا في القرن الثامن ورد اسمه في وثائق قليلة، ويُختلف في ترتيبه بين الحكام.",
   "at": "event",
   "died": 740
  },
  {
   "n": "سيفار",
   "trait": "swift",
   "flaw": null,
   "lead": 2,
   "fame": 30,
   "src": "hist",
   "wiki": "Sevar_of_Bulgaria",
   "ar": "سيفار",
   "bio": "حاكم لبلغاريا في القرن الثامن.",
   "at": "event",
   "died": 753
  },
  {
   "n": "قتلو خان",
   "trait": "swift",
   "flaw": "harsh",
   "lead": 2,
   "fame": 0,
   "src": "fic",
   "wiki": null,
   "ar": null,
   "bio": "شخصية متخيَّلة من صنع اللعبة، لا تستند إلى سيرة تاريخية.",
   "at": "event"
  },
  {
   "n": "باياندور",
   "trait": "archer",
   "flaw": null,
   "lead": 2,
   "fame": 0,
   "src": "fic",
   "wiki": null,
   "ar": null,
   "bio": "شخصية متخيَّلة من صنع اللعبة، لا تستند إلى سيرة تاريخية.",
   "at": "event"
  },
  {
   "n": "بوريسلاف",
   "trait": "brave",
   "flaw": null,
   "lead": 2,
   "fame": 0,
   "src": "fic",
   "wiki": null,
   "ar": null,
   "bio": "شخصية متخيَّلة من صنع اللعبة، لا تستند إلى سيرة تاريخية.",
   "at": "event"
  },
  {
   "n": "شهريار الديلمي",
   "trait": "mountaineer",
   "flaw": "greedy",
   "lead": 2,
   "fame": 0,
   "src": "fic",
   "wiki": null,
   "ar": null,
   "bio": "شخصية متخيَّلة من صنع اللعبة، لا تستند إلى سيرة تاريخية.",
   "at": "event"
  },
  {
   "n": "غريغور الأرمني",
   "trait": "cavalier",
   "flaw": "greedy",
   "lead": 2,
   "fame": 0,
   "src": "fic",
   "wiki": null,
   "ar": null,
   "bio": "شخصية متخيَّلة من صنع اللعبة، لا تستند إلى سيرة تاريخية.",
   "at": "event"
  }
 ]
};
