'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'C:/Users/Abdul/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{
 const out=path.resolve(__dirname,'../artifacts/economy');fs.mkdirSync(out,{recursive:true});
 const browser=await chromium.launch({headless:true,channel:'msedge'}),page=await browser.newPage({viewport:{width:1440,height:900},hasTouch:true}),errors=[],checks=[];
 page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8000',{waitUntil:'domcontentloaded'});await page.evaluate(()=>document.fonts.ready);
 async function start(){await page.evaluate(()=>{document.querySelectorAll('.modal-layer').forEach(e=>e.remove());Undo.clear();Game.newGame('umayyad','umayyad','normal');Game.f('umayyad').gold=5000;Game.financeState('umayyad').anchor=5000;Game.node('kufa').market=0;Game.endRound();const sc=new CampaignScene();sc.introShown=true;App.setScene(sc);Sheets.open(Panels.kingdomSpec(sc,'budget'));});await page.waitForTimeout(100);}
 async function check(name,w,h,selector='.sheet'){
  const m=await page.locator(selector).last().evaluate(el=>{const r=el.getBoundingClientRect(),body=el.querySelector('.sheet-body,.modal-body')||el;return {fits:r.left>=-1&&r.top>=-1&&r.right<=innerWidth+1&&r.bottom<=innerHeight+1,overflow:body.scrollWidth>body.clientWidth+2,direction:getComputedStyle(el).direction,minTarget:Math.min(...[...el.querySelectorAll('.eco-view button,.eco-view select,.eco-view summary,.modal-btns button')].filter(x=>x.getClientRects().length).map(x=>x.getBoundingClientRect().height))};});
  await page.screenshot({path:path.join(out,`${name}-${w}x${h}.png`)});
  if(m.overflow)console.log(await page.locator(selector).last().evaluate(el=>[...el.querySelectorAll('*')].filter(x=>x.clientWidth&&x.scrollWidth>x.clientWidth+2).slice(0,12).map(x=>({tag:x.tagName,cls:x.className,w:x.clientWidth,sw:x.scrollWidth,text:x.textContent.slice(0,90)}))));
  assert.ok(m.fits&&!m.overflow,`${name} ${w}x${h}: ${JSON.stringify(m)}`);assert.equal(m.direction,'rtl');if(Number.isFinite(m.minTarget))assert.ok(m.minTarget>=43,`${name}: target ${m.minTarget}`);return m;
 }
 async function tap(locator){await locator.scrollIntoViewIfNeeded();await locator.tap();}
 const mobileOnly=process.argv.includes('--mobile');
 for(const [w,h]of [[1440,900],[1024,768],[390,844],[360,740],[320,568],[844,390],[568,320]].filter(([w])=>!mobileOnly||w<1000)){
  await page.setViewportSize({width:w,height:h});await start();const result={viewport:[w,h]};result.treasury=await check('treasury',w,h);
  const ledger=page.locator('#eco-treasury summary').filter({hasText:'سجل التحصيل والقرارات'});await tap(ledger);assert.equal(await ledger.evaluate(x=>x.parentElement.open),true);result.ledger=await check('ledger',w,h);
  await tap(page.getByRole('button',{name:'شرح التكاليف',exact:true}));result.explanation=await check('explanation',w,h,'.modal');await tap(page.locator('.modal').getByRole('button',{name:'إغلاق',exact:true}));
  await tap(page.getByRole('button',{name:'قارن فرص الاستثمار',exact:true}));result.investment=await check('investment',w,h,'.modal');await page.getByLabel('المدينة',{exact:true}).selectOption('kufa');await page.getByLabel('نوع البناء',{exact:true}).selectOption('farm');assert.ok(await page.locator('.eco-invest button').count());await page.getByLabel('نوع البناء',{exact:true}).selectOption('market');await tap(page.locator('.eco-invest button').first());result.building=await check('building',w,h,'.modal');
  const gold=await page.evaluate(()=>Game.f('umayyad').gold);await tap(page.getByRole('button',{name:'ابدأ البناء',exact:true}));assert.equal(await page.evaluate(()=>Game.f('umayyad').gold),gold-300);assert.equal(await page.evaluate(()=>Game.node('kufa').work.b),'market');
  await page.evaluate(()=>{const n=Game.S.route.path.map(id=>Game.node(id)).find(n=>n.owner===Game.S.player);n.caravanStop=Game.S.turn+2;Panels.openRoute(App.scene);});await page.waitForFunction(()=>!document.getElementById('toast')||document.getElementById('toast').hidden);result.caravan=await check('caravan',w,h);assert.ok(await page.locator('#eco-caravan').textContent().then(s=>s.includes('تخريب')));
  const sections=page.locator('#eco-caravan summary').filter({hasText:'كل مقاطع الطريق'});await tap(sections);assert.equal(await sections.evaluate(x=>x.parentElement.open),true);result.caravanSegments=await check('caravan-segments',w,h);await tap(sections);
  await page.evaluate(()=>{const n=Game.node('amorium');n.prevOwner=n.owner;n.owner=Game.S.player;n.unrest=4;Game.capCtx={node:n.id,defMen:120,bldBefore:[2,1,1,0]};window.occupationResult=null;Panels.occupation(n,'storm').then(x=>window.occupationResult=x);});result.occupation=await check('occupation',w,h,'.modal');
  await tap(page.locator('.modal .seg button').filter({hasText:'الأمان'}));await tap(page.locator('.modal .seg button').filter({hasText:'أسر'}));result.aman=await check('aman',w,h,'.modal');await tap(page.getByRole('button',{name:'نفّذ',exact:true}));assert.equal(await page.evaluate(()=>window.occupationResult.choice),'clemency');assert.equal(await page.evaluate(()=>window.occupationResult.fate),'captives');await tap(page.locator('.sheet .head-btns button[title="إغلاق"]'));assert.ok(await page.locator('.map-tools').isVisible(),'map controls return after closing the economic sheet');await page.waitForFunction(()=>{const m=document.querySelector('.map-tools').getBoundingClientRect(),hud=document.querySelector('.hud-res').getBoundingClientRect();return m.top>=hud.bottom&&m.bottom<=innerHeight});checks.push(result);console.log('PASS UI '+w+'x'+h);
 }
 const saved=await page.evaluate(()=>{Game.capCtx=null;Game.save('slot3');return {gold:Game.f(Game.S.player).gold,economy:Game.economy(Game.S.player),ledger:Game.financeState(Game.S.player),city:Game.node('kufa'),route:Game.routeStatus(Game.S.player)};});
 for(let i=0;i<2;i++){await page.reload({waitUntil:'domcontentloaded'});const loaded=await page.evaluate(()=>{Game.load('slot3');return {gold:Game.f(Game.S.player).gold,economy:Game.economy(Game.S.player),ledger:Game.financeState(Game.S.player),city:Game.node('kufa'),route:Game.routeStatus(Game.S.player)};});assert.deepEqual(loaded,saved);}
 await browser.close();assert.deepEqual(errors,[]);const report=path.join(out,'visual-verification.json'),retained=mobileOnly&&fs.existsSync(report)?JSON.parse(fs.readFileSync(report,'utf8')).checks.filter(c=>c.viewport[0]>=1000):[];fs.writeFileSync(report,JSON.stringify({checks:[...retained,...checks],saveReloads:2,errors},null,2));console.log('Economy visual checks passed: '+checks.length+' viewports this run; '+retained.length+' unchanged desktop checks retained; two browser save/load passes.');
})().catch(e=>{console.error(e);process.exit(1)});
