'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');const {chromium}=require('C:/Users/Abdul/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
let previewBrowser;
(async()=>{
 const out=path.resolve(__dirname,'../artifacts/politics');fs.mkdirSync(out,{recursive:true});const browser=previewBrowser=await chromium.launch({headless:true,channel:'msedge'}),page=await browser.newPage({viewport:{width:1440,height:900},hasTouch:true}),errors=[],checks=[];
 page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8000',{waitUntil:'domcontentloaded'});await page.evaluate(()=>document.fonts.ready);
 async function start(){await page.evaluate(()=>{document.querySelectorAll('.modal-layer').forEach(e=>e.remove());if(document.getElementById('toast'))document.getElementById('toast').hidden=true;Game.newGame('umayyad','umayyad','normal');Game.normalizeState();Game.f('umayyad').gold=4000;Game.f('byzantine').gold=4000;Game.S.leaders.seed=12345;Game.node('nicaea').market=2;Game.node('damascus').marketOff=3;Game.rememberDiplomacy('byzantine','umayyad','kept',8,'حافظ على عهد سابق','visual');const s=new CampaignScene();s.introShown=true;App.setScene(s);s.openDiplo('byzantine');});await page.waitForTimeout(80);}
 async function tap(l){await l.scrollIntoViewIfNeeded();await l.tap();}
 async function check(name,w,h,sel='.modal'){
  const report=await page.locator(sel).last().evaluate(el=>{const r=el.getBoundingClientRect(),body=el.querySelector('.modal-body,.sheet-body')||el;const targets=[...el.querySelectorAll('button,select,summary')].filter(e=>e.getClientRects().length);return {fits:r.left>=-1&&r.top>=-1&&r.right<=innerWidth+1&&r.bottom<=innerHeight+1,overflow:body.scrollWidth>body.clientWidth+2,direction:getComputedStyle(el).direction,minTarget:Math.min(...targets.map(e=>e.getBoundingClientRect().height)),clippedControls:targets.filter(e=>{const a=e.getBoundingClientRect();return a.left<r.left-1||a.right>r.right+1}).map(e=>e.textContent.slice(0,50))};});
  await page.screenshot({path:path.join(out,`${name}-${w}x${h}.png`)});assert.ok(report.fits&&!report.overflow,`${name} ${w}x${h}: ${JSON.stringify(report)}`);assert.equal(report.direction,'rtl');assert.ok(report.minTarget>=43,`${name}: ${report.minTarget}`);assert.deepEqual(report.clippedControls,[]);assert.ok(!/\bnull\b|undefined|\[object|Wikipedia|https?:\/\//i.test(await page.locator(sel).last().textContent()),name+' placeholder/source text');return report;
 }
 for(const [w,h]of [[1440,900],[1024,768],[390,844],[360,740],[320,568],[844,390],[568,320]]){
  await page.setViewportSize({width:w,height:h});await start();const result={viewport:[w,h]};result.diplomacy=await check('diplomacy',w,h,'.sheet');
  await tap(page.getByRole('button',{name:'مفاوضات الصلح',exact:true}));result.peace=await check('peace',w,h);
  const slider=page.getByLabel('مبلغ عرض الصلح');await slider.scrollIntoViewIfNeeded();const rect=await slider.boundingBox(),before=await slider.inputValue();await page.touchscreen.tap(rect.x+rect.width*.92,rect.y+rect.height*.5);const after=await slider.inputValue();assert.notEqual(after,before);assert.ok(await page.locator('.pol-offer-value').textContent().then(s=>s.includes('تدفع')));
  await tap(page.getByText('شروط إضافية للاتفاق',{exact:true}));await tap(page.getByLabel('أقساط الصلح'));assert.ok(await page.locator('.pol-offer-value').textContent().then(s=>s.includes('المجموع')));await page.getByLabel('مدة الهدنة').selectOption('12');await page.getByLabel('التنازل عن مدينة').selectOption('amorium');result.peaceTerms=await check('peace-terms',w,h);await page.getByLabel('التنازل عن مدينة').selectOption('');await tap(page.getByLabel('أقساط الصلح'));await tap(page.getByRole('button',{name:'أرسل عرض الصلح',exact:true}));
  if(await page.getByRole('button',{name:'اقبل العرض المضاد',exact:true}).count())await tap(page.getByRole('button',{name:'اقبل العرض المضاد',exact:true}));assert.equal(await page.evaluate(()=>Game.atWar('umayyad','byzantine')),false);assert.equal(await page.evaluate(()=>Game.f('umayyad').truce.byzantine)>=8,true);
  await start();await page.evaluate(()=>{const c=Game.peaceCounter('umayyad','byzantine');Panels.counterDialog(App.scene,'byzantine',{counter:c,c:Game.peaceChance('byzantine','umayyad',c)});});result.counter=await check('counter',w,h);await tap(page.getByRole('button',{name:'اقبل العرض المضاد',exact:true}));assert.equal(await page.evaluate(()=>Game.atWar('umayyad','byzantine')),false);
  await start();await tap(page.getByRole('button',{name:'عمليات سرية',exact:true}));await tap(page.getByRole('button',{name:'تحريض',exact:true}));await page.getByLabel('هدف العملية').selectOption('nicaea');result.spy=await check('espionage',w,h);await tap(page.getByRole('button',{name:'تخريب',exact:true}));await page.getByLabel('هدف العملية').selectOption('nicaea');await page.getByLabel('نوع التخريب').selectOption('market');result.sabotage=await check('sabotage',w,h);const gold=await page.evaluate(()=>Game.f('umayyad').gold);await tap(page.getByRole('button',{name:'نفّذ العملية',exact:true}));assert.equal(await page.evaluate(()=>Game.f('umayyad').gold),gold-110);assert.equal(await page.evaluate(()=>Game.f('umayyad').spyTurn),0);result.spyResult=await check('spy-result',w,h);await tap(page.getByRole('button',{name:'حسناً',exact:true}));
  await tap(page.getByText('الرصد وحماية المدن',{exact:true}));await tap(page.getByRole('button',{name:'حماية المدن وإصلاح التخريب',exact:true}));await page.getByLabel('المدينة المحمية').selectOption('damascus');result.security=await check('counterspy',w,h);await tap(page.getByRole('button',{name:'نظّم التفتيش والحراسة',exact:true}));assert.equal(await page.evaluate(()=>Game.node('damascus').marketOff),0);
  await tap(page.getByRole('button',{name:'مفاوضة التبعية والحماية',exact:true}));result.vassal=await check('vassalage',w,h);await tap(page.locator('.modal').getByRole('button',{name:'إغلاق',exact:true}));
  await page.evaluate(()=>{Game.setStatus('umayyad','byzantine','peace',0);Game.f('umayyad').truce.byzantine=0;Game.f('byzantine').truce.umayyad=0;App.scene.openDiplo('byzantine')});await tap(page.getByRole('button',{name:'عرض حلف',exact:true}));result.alliance=await check('alliance',w,h);await tap(page.getByRole('button',{name:'أرسل العرض',exact:true}));assert.equal(await page.evaluate(()=>Game.diplomaticWait('umayyad','byzantine')),3);
  await page.evaluate(()=>{const o=Game.registerPoliticalOffer('byzantine','umayyad','trade');Panels.offerDialog(App.scene,o);});result.incoming=await check('incoming',w,h);await tap(page.getByRole('button',{name:'اقبل الشروط',exact:true}));assert.equal(await page.evaluate(()=>Game.treaty('umayyad','byzantine').trade),true);
  await page.evaluate(()=>{if(Game.atWar('umayyad','byzantine'))Game.makePeace('umayyad','byzantine',8);if(Game.status('umayyad','byzantine')!=='alliance')Game.makeAlliance('umayyad','byzantine');Game.setStatus('byzantine','khazar','war',0);Game.f('byzantine').rel.umayyad=60;Game.f('umayyad').rel.byzantine=60;Game.armiesOf('byzantine')[1].node='caesarea';const threat=Game.armiesOf('khazar')[0];threat.node='tarsus';threat.siege={turns:0,from:'caesarea'};threat.regs.forEach(r=>r.men=8);Panels.coordDialog(App.scene,'byzantine');});await tap(page.locator('.modal').getByRole('button',{name:'الدفاع عن مدينة',exact:true}));const coordRow=page.locator('.coord-row').filter({hasText:'طرسوس'});await coordRow.scrollIntoViewIfNeeded();result.coordination=await check('coordination',w,h);assert.notEqual(await coordRow.getByRole('button',{name:'اطلب',exact:true}).getAttribute('aria-disabled'),'true');await tap(coordRow.getByRole('button',{name:'اطلب',exact:true}));assert.ok(await page.evaluate(()=>Game.S.coord.some(c=>c.ok&&c.target==='tarsus')));
  checks.push(result);console.log('PASS political UI '+w+'x'+h);
 }
 const saved=await page.evaluate(()=>{Game.registerPoliticalOffer('byzantine','umayyad','marriage');Game.save('3');return {politics:Game.S.politics,wars:Game.S.wars,spy:Game.f('umayyad').spyTargetWait,city:Game.node('damascus'),tributes:Game.S.tributes,gold:Game.f('umayyad').gold};});
 for(let i=0;i<2;i++){await page.reload({waitUntil:'domcontentloaded'});const loaded=await page.evaluate(()=>{Game.load('3');return {politics:Game.S.politics,wars:Game.S.wars,spy:Game.f('umayyad').spyTargetWait,city:Game.node('damascus'),tributes:Game.S.tributes,gold:Game.f('umayyad').gold};});assert.deepEqual(loaded,saved);}
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'visual-results.json'),JSON.stringify({checks,saveReloads:2,errors},null,2));await browser.close();console.log('Political visuals, real touch/slider/select/confirm actions and two page reloads passed.');
})().catch(async e=>{console.error(e);await previewBrowser?.close();process.exitCode=1;});
